#! /bin/sh -f


# Train Command w/o learnable uncertainty weight loss
# Slow Improve
#CUDA_VISIBLE_DEVICES=4 python ./main.py --lr_enc 1e-4 --cas_min_lr_enc 8e-5 --cas_final_lr_enc 3e-6 --lr_dec 3e-4 --cas_min_lr_dec 1e-5 --cas_final_lr_dec 7e-6 --cas_warmup_steps_enc 50 --cas_warmup_steps_dec 180 --max_iter 2301 --cas_T_0_enc 2301 --cas_T_0_dec 2301 --load_init 1 --load_pretrained 1 --load_resume 0 --init_chkpt_file_enc ./weights/pretrained_hydranet_encoder.320_256.multiscale_dense.pth.tar --out_chkpt_file checkpoint.pretrained.encoder_multiscale_dense.decoder_rand.pth.tar --val_every 100 --freeze_enc_epoch 200 --output_dir ./pretrain_multiscale_dense_enc_rand_dec6 --batch_size 2

# Explode 
#CUDA_VISIBLE_DEVICES=3 python ./main.py --lr_enc 2e-4 --cas_min_lr_enc 5e-5 --cas_final_lr_enc 3e-6 --lr_dec 5e-4 --cas_min_lr_dec 5e-5 --cas_final_lr_dec 7e-6 --cas_warmup_steps_enc 100 --cas_warmup_steps_dec 180 --max_iter 2301 --cas_T_0_enc 2301 --cas_T_0_dec 2301 --load_init 1 --load_pretrained 1 --load_resume 0 --init_chkpt_file_enc ./weights/pretrained_hydranet_encoder.320_256.epoch10000.multiscale_dense.pth.tar --out_chkpt_file checkpoint.pretrained.encoder_multiscale_dense.decoder_rand.pth.tar --val_every 100 --freeze_enc_epoch 250 --output_dir ./pretrain_multiscale_dense_enc_rand_epoch10000_bz4_dec7 --batch_size 4

# Too Slow Improve
#CUDA_VISIBLE_DEVICES=3 python ./main.py --lr_enc 1.5e-4 --cas_min_lr_enc 5e-5 --cas_final_lr_enc 3e-6 --lr_dec 6e-4 --cas_min_lr_dec 6e-5 --cas_final_lr_dec 7e-6 --cas_warmup_steps_enc 100 --cas_warmup_steps_dec 180 --max_iter 2301 --cas_T_0_enc 2301 --cas_T_0_dec 2301 --load_init 1 --load_pretrained 1 --load_resume 0 --init_chkpt_file_enc ./weights/pretrained_hydranet_encoder.320_256.epoch10000.multiscale_dense.pth.tar --out_chkpt_file checkpoint.pretrained.encoder_multiscale_dense.decoder_rand.pth.tar --val_every 100 --freeze_enc_epoch 200 --output_dir ./pretrain_multiscale_dense_enc_rand_epoch10000_bz4_dec7 --batch_size 4

# Explode
 #CUDA_VISIBLE_DEVICES=3 python ./main.py --lr_enc 1.5e-4 --cas_min_lr_enc 5e-5 --cas_final_lr_enc 3e-6 --lr_dec 6e-4 --cas_min_lr_dec 6e-5 --cas_final_lr_dec 7e-6 --cas_warmup_steps_enc 100 --cas_warmup_steps_dec 180 --max_iter 2301 --cas_T_0_enc 2301 --cas_T_0_dec 2301 --load_init 1 --load_pretrained 1 --load_resume 0 --init_chkpt_file_enc ./weights/pretrained_hydranet_encoder.320_256.epoch10000.multiscale_dense.pth.tar --out_chkpt_file checkpoint.pretrained.encoder_multiscale_dense.decoder_rand.pth.tar --val_every 100 --freeze_enc_epoch 200 --output_dir ./pretrain_multiscale_dense_enc_rand_epoch10000_bz4_dec7_lrenc1.5e-4_minlrenc5e-5_lrdec6e-4_minlrdec6e-5 --batch_size 4

# Too Slow Converge
# CUDA_VISIBLE_DEVICES=3 python ./main.py --lr_enc 1.2e-4 --cas_min_lr_enc 4e-5 --cas_final_lr_enc 3e-6 --lr_dec 4e-4 --cas_min_lr_dec 6e-5 --cas_final_lr_dec 7e-6 --cas_warmup_steps_enc 100 --cas_warmup_steps_dec 180 --max_iter 2301 --cas_T_0_enc 1000 --cas_T_0_dec 1000 --load_init 1 --load_pretrained 1 --load_resume 0 --init_chkpt_file_enc ./weights/pretrained_hydranet_encoder.320_256.epoch10000.multiscale_dense.pth.tar --out_chkpt_file checkpoint.pretrained.encoder_multiscale_dense.decoder_rand.pth.tar --val_every 100 --freeze_enc_epoch 100 --output_dir ./pretrain_multiscale_dense_enc_rand_epoch10000_bz4_dec7_lrenc1.2e-4_minlrenc4e-5_finlrenc3e-6_lrdec4e-4_minlrdec6e-5_finlrdec7e-6/ --batch_size 4 --final_linear_decay

# test eval -> meaniou: 0.264309, rmse: 1.174679
 #CUDA_VISIBLE_DEVICES=3 python ./main.py --lr_enc 1.2e-4 --cas_min_lr_enc 8e-5 --cas_final_lr_enc 1e-5 --lr_dec 4e-4 --cas_min_lr_dec 1e-4 --cas_final_lr_dec 1e-5 --cas_warmup_steps_enc 100 --cas_warmup_steps_dec 180 --max_iter 2301 --cas_T_0_enc 300 --cas_T_0_dec 300 --load_init 1 --load_pretrained 1 --load_resume 0 --init_chkpt_file_enc ./weights/pretrained_hydranet_encoder.320_256.epoch10000.multiscale_dense.pth.tar --out_chkpt_file checkpoint.pretrained.encoder_multiscale_dense.decoder_rand.pth.tar --val_every 100 --freeze_enc_epoch 30 --lr_sigma_seg 5e-4 --cas_min_lr_sigma_seg 5e-5 --cas_final_lr_sigma_seg 1e-5 --lr_sigma_depth 5e-4 --cas_min_lr_sigma_depth 5e-5 --cas_final_lr_sigma_depth 1e-5 --cas_warmup_steps_sigma_seg 100 --cas_warmup_steps_sigma_depth 100 --cas_T_0_sigma_seg 400 --cas_T_0_sigma_depth 400  --output_dir ./pretrain_multiscale_dense_enc_rand_epoch10000_bz4_dec7_lrenc1.2e-4_minlrenc8e-5_finlrenc1e-5_lrdec4e-4_minlrdec1e-4_finlrdec1e-5_wsigmalrsegdepth/ --batch_size 4 --final_linear_decay


# use depth_loss = learn1*invhuber_loss + learn2*l1_loss + learn3*grad_loss
CUDA_VISIBLE_DEVICES=3 python ./main.py --lr_enc 1.2e-4 --cas_min_lr_enc 8e-5 --cas_final_lr_enc 1e-5 --lr_dec 4e-4 --cas_min_lr_dec 1e-4 --cas_final_lr_dec 1e-5 --cas_warmup_steps_enc 100 --cas_warmup_steps_dec 180 --max_iter 2301 --cas_T_0_enc 300 --cas_T_0_dec 300 --load_init 1 --load_pretrained 1 --load_resume 0 --init_chkpt_file_enc ./weights/pretrained_hydranet_encoder.320_256.epoch10000.multiscale_dense.pth.tar --out_chkpt_file checkpoint.pretrained.encoder_multiscale_dense.decoder_rand.pth.tar --val_every 100 --freeze_enc_epoch 30 --lr_sigma_seg 5e-4 --cas_min_lr_sigma_seg 5e-5 --cas_final_lr_sigma_seg 1e-5 --lr_sigma_depth 5e-4 --cas_min_lr_sigma_depth 5e-5 --cas_final_lr_sigma_depth 1e-5 --cas_warmup_steps_sigma_seg 100 --cas_warmup_steps_sigma_depth 100 --cas_T_0_sigma_seg 400 --cas_T_0_sigma_depth 400 --output_dir ./pretrain_multiscale_dense_enc_rand_epoch10000_bz4_dec7_lrenc1.2e-4_minlrenc8e-5_finlrenc1e-5_lrdec4e-4_minlrdec1e-4_finlrdec1e-5_wsigmalrsegdepth_useunclossw_wdcyenc2e-4_wdcydec3e-5_depthlossl1grad/ --batch_size 4 --final_linear_decay --use_uncloss_weight --weight_decay_enc 2e-4 --weight_decay_dec 3e-4 --weight_decay_dec_depthloss 0 --use_learnw_invhub_l1_grad --invhuber_weight 0.6 --l1_weight 0.3 --grad_weight 0.1

# use depth_loss = learn1*invhuber_loss + learn2*l1_loss + learn3*grad_loss
# use cos_anneal_restart
CUDA_VISIBLE_DEVICES=3 python ./main.py --lr_enc 1.2e-4 --cas_min_lr_enc 8e-5 --cas_final_lr_enc 1e-5 --lr_dec 4e-4 --cas_min_lr_dec 1e-4 --cas_final_lr_dec 1e-5 --cas_warmup_steps_enc 100 --cas_warmup_steps_dec 180 --max_iter 2301 --cas_T_0_enc 300 --cas_T_0_dec 300 --load_init 1 --load_pretrained 1 --load_resume 0 --init_chkpt_file_enc ./weights/pretrained_hydranet_encoder.320_256.epoch10000.multiscale_dense.pth.tar --out_chkpt_file checkpoint.pretrained.encoder_multiscale_dense.decoder_rand.pth.tar --val_every 100 --freeze_enc_epoch 30 --lr_sigma_seg 5e-4 --cas_min_lr_sigma_seg 5e-5 --cas_final_lr_sigma_seg 1e-5 --lr_sigma_depth 5e-4 --cas_min_lr_sigma_depth 5e-5 --cas_final_lr_sigma_depth 1e-5 --cas_warmup_steps_sigma_seg 100 --cas_warmup_steps_sigma_depth 100 --cas_T_0_sigma_seg 400 --cas_T_0_sigma_depth 400 --output_dir ./pretrain_multiscale_dense_enc_rand_epoch10000_bz4_dec7_lrenc1.2e-4_minlrenc8e-5_finlrenc1e-5_lrdec4e-4_minlrdec1e-4_finlrdec1e-5_wsigmalrsegdepth_useunclossw_wdcyenc2e-4_wdcydec3e-5_depthlossl1grad_cosannealrestart/ --batch_size 4 --use_uncloss_weight --weight_decay_enc 2e-4 --weight_decay_dec 3e-4 --weight_decay_dec_depthloss 0 --cos_anneal_restart --use_learnw_invhub_l1_grad --invhuber_weight 0.6 --l1_weight 0.3 --grad_weight 0.1


# use depth_loss = cnst1*invhuber_loss + cnst2*l1_loss + cnst3*grad_loss
# use cos_anneal_restart
# use const learn weight of depth loss: invhub+l1+grad
# test eval, meaniou: 0.270280, rmse: 0.783463
#CUDA_VISIBLE_DEVICES=3 python ./main.py --lr_enc 1.2e-4 --cas_min_lr_enc 8e-5 --cas_final_lr_enc 1e-5 --lr_dec 4e-4 --cas_min_lr_dec 1e-4 --cas_final_lr_dec 1e-5 --cas_warmup_steps_enc 100 --cas_warmup_steps_dec 180 --max_iter 2301 --cas_T_0_enc 300 --cas_T_0_dec 300 --load_init 1 --load_pretrained 1 --load_resume 0 --init_chkpt_file_enc ./weights/pretrained_hydranet_encoder.320_256.epoch10000.multiscale_dense.pth.tar --out_chkpt_file checkpoint.pretrained.encoder_multiscale_dense.decoder_rand.pth.tar --val_every 100 --freeze_enc_epoch 30 --lr_sigma_seg 5e-4 --cas_min_lr_sigma_seg 5e-5 --cas_final_lr_sigma_seg 1e-5 --lr_sigma_depth 5e-4 --cas_min_lr_sigma_depth 5e-5 --cas_final_lr_sigma_depth 1e-5 --cas_warmup_steps_sigma_seg 100 --cas_warmup_steps_sigma_depth 100 --cas_T_0_sigma_seg 400 --cas_T_0_sigma_depth 400 --output_dir ./pretrain_multiscale_dense_enc_rand_epoch10000_bz4_dec7_lrenc1.2e-4_minlrenc8e-5_finlrenc1e-5_lrdec4e-4_minlrdec1e-4_finlrdec1e-5_wsigmalrsegdepth_useunclossw_wdcyenc2e-4_wdcydec3e-5_depthlossl1grad_cosannealrestart_usecnst_0.6_0.3_0.1/ --batch_size 4 --use_uncloss_weight --weight_decay_enc 2e-4 --weight_decay_dec 3e-4 --cos_anneal_restart --invhuber_weight 0.6 --l1_weight 0.3 --grad_weight 0.1

# use depth_loss = cnst1*invhuber_loss + cnst2*l1_loss + cnst3*grad_loss
# use cos_anneal_restart
# use const learn weight of depth loss: invhub+l1+grad
CUDA_VISIBLE_DEVICES=1 python ./main.py --lr_enc 1.2e-4 --cas_min_lr_enc 8e-5 --cas_final_lr_enc 1e-5 --lr_dec 6e-4 --cas_min_lr_dec 3e-4 --cas_final_lr_dec 1e-5 --cas_warmup_steps_enc 100 --cas_warmup_steps_dec 180 --max_iter 2301 --cas_T_0_enc 300 --cas_T_0_dec 300 --load_init 1 --load_pretrained 1 --load_resume 0 --init_chkpt_file_enc ./weights/pretrained_hydranet_encoder.320_256.epoch10000.multiscale_dense.pth.tar --out_chkpt_file checkpoint.pretrained.encoder_multiscale_dense.decoder_rand.pth.tar --val_every 100 --freeze_enc_epoch 30 --lr_sigma_seg 5e-4 --cas_min_lr_sigma_seg 5e-5 --cas_final_lr_sigma_seg 1e-5 --lr_sigma_depth 5e-4 --cas_min_lr_sigma_depth 5e-5 --cas_final_lr_sigma_depth 1e-5 --cas_warmup_steps_sigma_seg 100 --cas_warmup_steps_sigma_depth 100 --cas_T_0_sigma_seg 400 --cas_T_0_sigma_depth 400 --output_dir ./pretrain_multiscale_dense_enc_rand_epoch10000_bz4_dec7_lrenc1.2e-4_minlrenc8e-5_finlrenc1e-5_lrdec6e-4_minlrdec3e-4_finlrdec1e-5_wsigmalrsegdepth_useunclossw_wdcyenc3e-4_wdcydec4e-5_depthlossl1grad_cosannealrestart_usecnst_0.6_0.3_0.1/ --batch_size 4 --use_uncloss_weight --weight_decay_enc 3e-4 --weight_decay_dec 4e-4 --cos_anneal_restart --invhuber_weight 0.6 --l1_weight 0.3 --grad_weight 0.1

# test eval, meaniou: 0.303592, rmse: 1.164320
 CUDA_VISIBLE_DEVICES=3 python ./main.py --lr_enc 1.2e-4 --cas_min_lr_enc 8e-5 --cas_final_lr_enc 1e-5 --lr_dec 4e-4 --cas_min_lr_dec 1e-4 --cas_final_lr_dec 1e-5 --cas_warmup_steps_enc 100 --cas_warmup_steps_dec 180 --max_iter 2301 --cas_T_0_enc 300 --cas_T_0_dec 300 --load_init 1 --load_pretrained 1 --load_resume 0 --init_chkpt_file_enc ./weights/pretrained_hydranet_encoder.320_256.epoch10000.multiscale_dense.pth.tar --out_chkpt_file checkpoint.pretrained.encoder_multiscale_dense.decoder_rand.pth.tar --val_every 100 --freeze_enc_epoch 30 --lr_sigma_seg 5e-4 --cas_min_lr_sigma_seg 5e-5 --cas_final_lr_sigma_seg 1e-5 --lr_sigma_depth 5e-4 --cas_min_lr_sigma_depth 5e-5 --cas_final_lr_sigma_depth 1e-5 --cas_warmup_steps_sigma_seg 100 --cas_warmup_steps_sigma_depth 100 --cas_T_0_sigma_seg 400 --cas_T_0_sigma_depth 400 --output_dir ./pretrain_multiscale_dense_enc_rand_epoch10000_bz4_dec7_lrenc1.2e-4_minlrenc8e-5_finlrenc1e-5_lrdec4e-4_minlrdec1e-4_finlrdec1e-5_wsigmalrsegdepth_useunclossw_wdcyenc2e-4_wdcydec3e-5/ --batch_size 4 --final_linear_decay --use_uncloss_weight --weight_decay_enc 2e-4 --weight_decay_dec 3e-4 --invhuber_weight 1.0 --l1_weight 0.0 --grad_weight 0.0

 # enc rand, dec rand
 #CUDA_VISIBLE_DEVICES=1 python ./main.py --lr_enc 1.2e-4 --cas_min_lr_enc 8e-5 --cas_final_lr_enc 1e-5 --lr_dec 4e-4 --cas_min_lr_dec 1e-4 --cas_final_lr_dec 1e-5 --cas_warmup_steps_enc 100 --cas_warmup_steps_dec 180 --max_iter 2301 --cas_T_0_enc 300 --cas_T_0_dec 300 --load_init 0 --load_pretrained 0 --load_resume 0 --out_chkpt_file checkpoint.pretrained.encoder_multiscale_dense.decoder_rand.pth.tar --val_every 100 --freeze_enc_epoch 0 --lr_sigma_seg 5e-4 --cas_min_lr_sigma_seg 5e-5 --cas_final_lr_sigma_seg 1e-5 --lr_sigma_depth 5e-4 --cas_min_lr_sigma_depth 5e-5 --cas_final_lr_sigma_depth 1e-5 --cas_warmup_steps_sigma_seg 100 --cas_warmup_steps_sigma_depth 100 --cas_T_0_sigma_seg 400 --cas_T_0_sigma_depth 400 --output_dir baseline_result_all_rand3 --batch_size 4 --final_linear_decay --weight_decay_enc 2e-4 --weight_decay_dec 3e-4 --invhuber_weight 1.0 --l1_weight 0.0 --grad_weight 0.0 --use_invhuber_only

 # enc rand, dec rand
 CUDA_VISIBLE_DEVICES=1 python ./main.py --lr_enc 1.2e-4 --cas_min_lr_enc 8e-5 --cas_final_lr_enc 1e-5 --lr_dec 4e-4 --cas_min_lr_dec 1e-4 --cas_final_lr_dec 1e-5 --cas_warmup_steps_enc 100 --cas_warmup_steps_dec 180 --max_iter 2301 --cas_T_0_enc 300 --cas_T_0_dec 300 --load_init 0 --load_pretrained 0 --load_resume 0 --out_chkpt_file checkpoint.pretrained.encoder_multiscale_dense.decoder_rand.pth.tar --val_every 100 --freeze_enc_epoch 0 --lr_sigma_seg 5e-4 --cas_min_lr_sigma_seg 5e-5 --cas_final_lr_sigma_seg 1e-5 --lr_sigma_depth 5e-4 --cas_min_lr_sigma_depth 5e-5 --cas_final_lr_sigma_depth 1e-5 --cas_warmup_steps_sigma_seg 100 --cas_warmup_steps_sigma_depth 100 --cas_T_0_sigma_seg 400 --cas_T_0_sigma_depth 400 --output_dir baseline_result_all_rand3_invhuberonly --batch_size 4 --final_linear_decay --weight_decay_enc 2e-4 --weight_decay_dec 3e-4 --invhuber_weight 1.0 --l1_weight 0.0 --grad_weight 0.0 --use_invhuber_only

# Same Setting as line 60
# eval test, meaniou: 0.289526, rmse: 1.183473
 CUDA_VISIBLE_DEVICES=3 python ./main.py --lr_enc 1e-4 --cas_min_lr_enc 8e-5 --cas_final_lr_enc 3e-6 --lr_dec 2e-4 --cas_min_lr_dec 1e-5 --cas_final_lr_dec 7e-6 --cas_warmup_steps_enc 50 --cas_warmup_steps_dec 100 --max_iter 2301 --cas_T_0_enc 1000 --cas_T_0_dec 1000 --load_init 1 --load_pretrained 1 --load_resume 0 --init_chkpt_file_enc ./weights/pretrained_hydranet_encoder.320_256.epoch10000.multiscale_dense.pth.tar --out_chkpt_file checkpoint.pretrained.encoder_multiscale_dense.decoder_rand.pth.tar --val_every 100 --freeze_enc_epoch 50 --lr_sigma_seg 5e-4 --cas_min_lr_sigma_seg 5e-5 --cas_final_lr_sigma_seg 1e-5 --lr_sigma_depth 5e-4 --cas_min_lr_sigma_depth 5e-5 --cas_final_lr_sigma_depth 1e-5 --cas_warmup_steps_sigma_seg 100 --cas_warmup_steps_sigma_depth 100 --cas_T_0_sigma_seg 300 --cas_T_0_sigma_depth 300 --output_dir ./pretrain_multiscale_dense_enc_rand_epoch10000_bz4_dec7_lrenc1e-4_minlrenc8e-5_finlrenc3e-6_lrdec2e-4_minlrdec1e-5_finlrdec7e-6_wsigmalrsegdepth_useunclossw_wdcyenc2e-4_wdcydec3e-4_samesetting/ --batch_size 4 --final_linear_decay --use_uncloss_weight --weight_decay_enc 2e-4 --weight_decay_dec 3e-4

# -- Dead and Resume Command
CUDA_VISIBLE_DEVICES=4 python ./main.py --lr_enc 1e-4 --cas_min_lr_enc 8e-5 --cas_final_lr_enc 3e-6 --lr_dec 3e-4 --cas_min_lr_dec 1e-5 --cas_final_lr_dec 7e-6 --cas_warmup_steps_enc 50 --cas_warmup_steps_dec 180 --max_iter 2301 --cas_T_0_enc 2301 --cas_T_0_dec 2301 --load_init 0 --load_pretrained 0 --load_resume 1 --init_chkpt_file_enc ./weights/pretrained_hydranet_encoder.320_256.multiscale_dense.pth.tar --out_chkpt_file ./pretrain_multiscale_dense_enc_rand_dec6/checkpoint.pretrained.encoder_multiscale_dense.decoder_rand.pth.tar --val_every 100 --freeze_enc_epoch 0 --output_dir ./pretrain_multiscale_dense_enc_rand_dec6 --batch_size 4

# -- new pretrained epoch 10000 feature
# Too Slow Improve
#CUDA_VISIBLE_DEVICES=3 python ./main.py --lr_enc 1e-4 --cas_min_lr_enc 8e-5 --cas_final_lr_enc 3e-6 --lr_dec 3e-4 --cas_min_lr_dec 4e-5 --cas_final_lr_dec 7e-6 --cas_warmup_steps_enc 50 --cas_warmup_steps_dec 180 --max_iter 2301 --cas_T_0_enc 2301 --cas_T_0_dec 2301 --load_init 1 --load_pretrained 1 --load_resume 0 --init_chkpt_file_enc ./weights/pretrained_hydranet_encoder.320_256.epoch10000.multiscale_dense.pth.tar --init_chkpt_file_dec ./weights/pretrained_hydranet_decoder.autoencoder.epoch10000.pth.tar --out_chkpt_file checkpoint.pretrained.encoder_multiscale_dense.decoder_autoencoder.epoch10000.pth.tar --val_every 100 --freeze_enc_epoch 300 --output_dir ./pretrain_multiscale_dense_enc_autoencoder_dec_ep10000_bz4_0 --batch_size 4

# Too Slow Improve
#CUDA_VISIBLE_DEVICES=3 python ./main.py --lr_enc 1e-4 --cas_min_lr_enc 8e-5 --cas_final_lr_enc 3e-6 --lr_dec 2e-4 --cas_min_lr_dec 1e-5 --cas_final_lr_dec 7e-6 --cas_warmup_steps_enc 50 --cas_warmup_steps_dec 180 --max_iter 2301 --cas_T_0_enc 2301 --cas_T_0_dec 2301 --load_init 1 --load_pretrained 1 --load_resume 0 --init_chkpt_file_enc ./weights/pretrained_hydranet_encoder.320_256.multiscale_dense.pth.tar --out_chkpt_file checkpoint.pretrained.encoder_multiscale_dense.decoder_rand.pth.tar --val_every 100 --freeze_enc_epoch 200 --output_dir ./pretrain_multiscale_dense_enc_rand_dec8_uncweightloss/ --batch_size 1 --use_uncloss_weight --weight_decay_enc 8e-4 --weight_decay_dec 3e-4

# Too Slow Improve
#CUDA_VISIBLE_DEVICES=3 python ./main.py --lr_enc 2e-4 --cas_min_lr_enc 8e-5 --cas_final_lr_enc 4e-6 --lr_dec 5e-4 --cas_min_lr_dec 5e-5 --cas_final_lr_dec 7e-6 --cas_warmup_steps_enc 100 --cas_warmup_steps_dec 180 --max_iter 2301 --cas_T_0_enc 2301 --cas_T_0_dec 2301 --load_init 1 --load_pretrained 1 --load_resume 0 --init_chkpt_file_enc ./weights/pretrained_hydranet_encoder.320_256.epoch10000.multiscale_dense.pth.tar --init_chkpt_file_dec ./weights/pretrained_hydranet_decoder.autoencoder.epoch10000.pth.tar --out_chkpt_file checkpoint.pretrained.encoder_multiscale_dense.decoder_autoencoder.epoch10000.pth.tar --val_every 100 --freeze_enc_epoch 200 --output_dir ./pretrain_multiscale_dense_enc_autoencoder_dec_ep10000_bz4_0 --batch_size 4

# Explode
#CUDA_VISIBLE_DEVICES=3 python ./main.py --lr_enc 5e-4 --cas_min_lr_enc 8e-5 --cas_final_lr_enc 4e-6 --lr_dec 6e-4 --cas_min_lr_dec 9e-5 --cas_final_lr_dec 7e-6 --cas_warmup_steps_enc 100 --cas_warmup_steps_dec 180 --max_iter 2301 --cas_T_0_enc 2301 --cas_T_0_dec 2301 --load_init 1 --load_pretrained 1 --load_resume 0 --init_chkpt_file_enc ./weights/pretrained_hydranet_encoder.320_256.epoch10000.multiscale_dense.pth.tar --init_chkpt_file_dec ./weights/pretrained_hydranet_decoder.autoencoder.epoch10000.pth.tar --out_chkpt_file checkpoint.pretrained.encoder_multiscale_dense.decoder_autoencoder.epoch10000.pth.tar --val_every 100 --freeze_enc_epoch 200 --output_dir ./pretrain_multiscale_dense_enc_autoencoder_dec_ep10000_bz4_lrenc5e-4_minlrenc8e-5_lrdec6e-4_minlrdec9e-5/ --batch_size 4

# Explode
#CUDA_VISIBLE_DEVICES=3 python ./main.py --lr_enc 2e-4 --cas_min_lr_enc 8e-5 --cas_final_lr_enc 4e-6 --lr_dec 6e-4 --cas_min_lr_dec 9e-5 --cas_final_lr_dec 7e-6 --cas_warmup_steps_enc 100 --cas_warmup_steps_dec 180 --max_iter 2301 --cas_T_0_enc 2301 --cas_T_0_dec 2301 --load_init 1 --load_pretrained 1 --load_resume 0 --init_chkpt_file_enc ./weights/pretrained_hydranet_encoder.320_256.epoch10000.multiscale_dense.pth.tar --init_chkpt_file_dec ./weights/pretrained_hydranet_decoder.autoencoder.epoch10000.pth.tar --out_chkpt_file checkpoint.pretrained.encoder_multiscale_dense.decoder_autoencoder.epoch10000.pth.tar --val_every 100 --freeze_enc_epoch 200 --output_dir ./pretrain_multiscale_dense_enc_autoencoder_dec_ep10000_bz4_lrenc2e-4_minlrenc8e-5_lrdec6e-4_minlrdec9e-5/ --batch_size 4

# Explode
#CUDA_VISIBLE_DEVICES=3 python ./main.py --lr_enc 2e-4 --cas_min_lr_enc 8e-5 --cas_final_lr_enc 4e-6 --lr_dec 3e-4 --cas_min_lr_dec 8e-5 --cas_final_lr_dec 7e-6 --cas_warmup_steps_enc 100 --cas_warmup_steps_dec 180 --max_iter 2301 --cas_T_0_enc 1000 --cas_T_0_dec 1000 --load_init 1 --load_pretrained 1 --load_resume 0 --init_chkpt_file_enc ./weights/pretrained_hydranet_encoder.320_256.epoch10000.multiscale_dense.pth.tar --init_chkpt_file_dec ./weights/pretrained_hydranet_decoder.autoencoder.epoch10000.pth.tar --out_chkpt_file checkpoint.pretrained.encoder_multiscale_dense.decoder_autoencoder.epoch10000.pth.tar --val_every 100 --freeze_enc_epoch 200 --output_dir ./pretrain_multiscale_dense_enc_autoencoder_dec_ep10000_bz4_lrenc2e-4_minlrenc8e-5_lrdec6e-4_minlrdec9e-5/ --batch_size 4 --final_linear_decay

#-------------------------------------------------------------------------------------------------------#
# Train Command w/ learnable uncertainty weight loss
# Explode
#CUDA_VISIBLE_DEVICES=4 python ./main.py --lr_enc 1e-4 --cas_min_lr_enc 8e-5 --cas_final_lr_enc 3e-6 --lr_dec 7e-4 --cas_min_lr_dec 9e-5 --cas_final_lr_dec 7e-6 --cas_warmup_steps_enc 50 --cas_warmup_steps_dec 180 --max_iter 2301 --cas_T_0_enc 2301 --cas_T_0_dec 2301 --load_init 1 --load_pretrained 1 --load_resume 0 --init_chkpt_file_enc ./weights/pretrained_hydranet_encoder.320_256.multiscale_dense.pth.tar --out_chkpt_file checkpoint.pretrained.encoder_multiscale_dense.decoder_rand.pth.tar --val_every 100 --freeze_enc_epoch 200 --output_dir ./pretrain_multiscale_dense_enc_rand_dec7_uncweightloss/ --batch_size 8 --use_uncloss_weight --weight_decay_enc 6e-4 --weight_decay_dec 3e-4

# test eval -> meaniou: 0.304979, rmse: 1.152711
CUDA_VISIBLE_DEVICES=3 python ./main.py --lr_enc 1e-4 --cas_min_lr_enc 8e-5 --cas_final_lr_enc 3e-6 --lr_dec 2e-4 --cas_min_lr_dec 1e-5 --cas_final_lr_dec 7e-6 --cas_warmup_steps_enc 50 --cas_warmup_steps_dec 180 --max_iter 2301 --cas_T_0_enc 1000 --cas_T_0_dec 1000 --load_init 1 --load_pretrained 1 --load_resume 0 --init_chkpt_file_enc ./weights/pretrained_hydranet_encoder.320_256.multiscale_dense.pth.tar --out_chkpt_file checkpoint.pretrained.encoder_multiscale_dense.decoder_rand.pth.tar --val_every 100 --freeze_enc_epoch 50 --output_dir ./pretrain_multiscale_dense_enc_rand_dec8_uncweightloss_lrenc1e-4_minlrenc8e-5_finlrenc3e-6_lrdec2e-4_minlrdec1e-5_finlrdec7e-6/ --batch_size 4 --use_uncloss_weight --weight_decay_enc 2e-4 --weight_decay_dec 3e-4 --final_linear_decay

# test eval, meaniou: 0.287099, rmse: 1.158603
CUDA_VISIBLE_DEVICES=3 python ./main.py --lr_enc 1e-4 --cas_min_lr_enc 8e-5 --cas_final_lr_enc 3e-6 --lr_dec 2e-4 --cas_min_lr_dec 1e-5 --cas_final_lr_dec 7e-6 --cas_warmup_steps_enc 50 --cas_warmup_steps_dec 180 --max_iter 2301 --cas_T_0_enc 1000 --cas_T_0_dec 1000 --load_init 1 --load_pretrained 1 --load_resume 0 --init_chkpt_file_enc ./weights/pretrained_hydranet_encoder.320_256.multiscale_dense.pth.tar --out_chkpt_file checkpoint.pretrained.encoder_multiscale_dense.decoder_rand.pth.tar --val_every 100 --freeze_enc_epoch 50 --output_dir ./pretrain_multiscale_dense_enc_rand_dec9_uncweightloss_lrenc1e-4_minlrenc8e-5_finlrenc3e-6_lrdec2e-4_minlrdec1e-5_finlrdec7e-6_wsigmalrsegdepth_wdcyenc2e-4_wdcydec3e-4/ --batch_size 4 --use_uncloss_weight --weight_decay_enc 2e-4 --weight_decay_dec 3e-4 --final_linear_decay --lr_sigma_seg 5e-4 --cas_min_lr_sigma_seg 5e-5 --cas_final_lr_sigma_seg 1e-5 --cas_T_0_sigma_seg 300 --cas_warmup_steps_sigma_seg 100 --lr_sigma_depth 5e-4 --cas_min_lr_sigma_depth 5e-5 --cas_final_lr_sigma_depth 1e-5 --cas_T_0_sigma_depth 300 --cas_warmup_steps_sigma_depth 100


# -- new pretrained epoch 10000 feature
#CUDA_VISIBLE_DEVICES=3 python ./main.py --lr_enc 1e-4 --cas_min_lr_enc 8e-5 --cas_final_lr_enc 3e-6 --lr_dec 3e-4 --cas_min_lr_dec 1e-5 --cas_final_lr_dec 7e-6 --cas_warmup_steps_enc 50 --cas_warmup_steps_dec 180 --max_iter 2301 --cas_T_0_enc 2301 --cas_T_0_dec 2301 --load_init 1 --load_pretrained 1 --load_resume 0 --init_chkpt_file_enc ./weights/pretrained_hydranet_encoder.320_256.epoch10000.multiscale_dense.pth.tar --init_chkpt_file_dec ./weights/pretrained_hydranet_decoder.autoencoder.epoch10000.pth.tar --out_chkpt_file checkpoint.pretrained.encoder_multiscale_dense.decoder_autoencoder.epoch10000.pth.tar --val_every 100 --freeze_enc_epoch 200 --output_dir ./pretrain_multiscale_dense_enc_autoencoder_dec_ep10000_bz1_uncweightloss_0/ --batch_size 1 --use_uncloss_weight --weight_decay_enc 8e-4 --weight_decay_dec 3e-4

# Explode
#CUDA_VISIBLE_DEVICES=3 python ./main.py --lr_enc 3e-4 --cas_min_lr_enc 8e-5 --cas_final_lr_enc 3e-6 --lr_dec 6e-4 --cas_min_lr_dec 6e-5 --cas_final_lr_dec 7e-6 --cas_warmup_steps_enc 50 --cas_warmup_steps_dec 180 --max_iter 2301 --cas_T_0_enc 2301 --cas_T_0_dec 2301 --load_init 1 --load_pretrained 1 --load_resume 0 --init_chkpt_file_enc ./weights/pretrained_hydranet_encoder.320_256.epoch10000.multiscale_dense.pth.tar --init_chkpt_file_dec ./weights/pretrained_hydranet_decoder.autoencoder.epoch10000.pth.tar --out_chkpt_file checkpoint.pretrained.encoder_multiscale_dense.decoder_autoencoder.epoch10000.pth.tar --val_every 100 --freeze_enc_epoch 200 --output_dir ./pretrain_multiscale_dense_enc_autoencoder_dec_ep10000_bz4_uncweightloss_lrenc3e-4_minlrenc8e-5_lrdec6e-4_minlrdec8e-5/ --batch_size 4 --use_uncloss_weight

# Explode
#CUDA_VISIBLE_DEVICES=3 python ./main.py --lr_enc 2e-4 --cas_min_lr_enc 8e-5 --cas_final_lr_enc 3e-6 --lr_dec 6e-4 --cas_min_lr_dec 6e-5 --cas_final_lr_dec 7e-6 --cas_warmup_steps_enc 50 --cas_warmup_steps_dec 180 --max_iter 2301 --cas_T_0_enc 2301 --cas_T_0_dec 2301 --load_init 1 --load_pretrained 1 --load_resume 0 --init_chkpt_file_enc ./weights/pretrained_hydranet_encoder.320_256.epoch10000.multiscale_dense.pth.tar --init_chkpt_file_dec ./weights/pretrained_hydranet_decoder.autoencoder.epoch10000.pth.tar --out_chkpt_file checkpoint.pretrained.encoder_multiscale_dense.decoder_autoencoder.epoch10000.pth.tar --val_every 100 --freeze_enc_epoch 50 --output_dir ./pretrain_multiscale_dense_enc_autoencoder_dec_ep10000_bz4_uncweightloss_lrenc2e-4_minlrenc8e-5_lrdec6e-4_minlrdec8e-5/ --batch_size 4 --use_uncloss_weight

# Explode
#CUDA_VISIBLE_DEVICES=3 python ./main.py --lr_enc 2e-4 --cas_min_lr_enc 8e-5 --cas_final_lr_enc 3e-6 --lr_dec 4e-4 --cas_min_lr_dec 7e-5 --cas_final_lr_dec 7e-6 --cas_warmup_steps_enc 50 --cas_warmup_steps_dec 180 --max_iter 2301 --cas_T_0_enc 1000 --cas_T_0_dec 1000 --load_init 1 --load_pretrained 1 --load_resume 0 --init_chkpt_file_enc ./weights/pretrained_hydranet_encoder.320_256.epoch10000.multiscale_dense.pth.tar --init_chkpt_file_dec ./weights/pretrained_hydranet_decoder.autoencoder.epoch10000.pth.tar --out_chkpt_file checkpoint.pretrained.encoder_multiscale_dense.decoder_autoencoder.epoch10000.pth.tar --val_every 100 --freeze_enc_epoch 100 --output_dir ./pretrain_multiscale_dense_enc_autoencoder_dec_ep10000_bz4_uncweightloss_lrenc2e-4_minlrenc8e-5_finlrenc3e-6_lrdec4e-4_minlrdec7e-5_finlrdec7e-6/ --batch_size  4--use_uncloss_weight --final_linear_decay

# test eval -> meaniou : 0.243688 | rmse : 1.172928
 CUDA_VISIBLE_DEVICES=3 python ./main.py --lr_enc 3e-4 --cas_min_lr_enc 8e-5 --cas_final_lr_enc 4e-6 --lr_dec 4e-4 --cas_min_lr_dec 8e-5 --cas_final_lr_dec 7e-6 --cas_warmup_steps_enc 100 --cas_warmup_steps_dec 180 --max_iter 2301 --cas_T_0_enc 1000 --cas_T_0_dec 1000 --load_init 1 --load_pretrained 1 --load_resume 0 --init_chkpt_file_enc ./weights/pretrained_hydranet_encoder.320_256.epoch10000.multiscale_dense.pth.tar --init_chkpt_file_dec ./weights/pretrained_hydranet_decoder.autoencoder.epoch10000.pth.tar --out_chkpt_file checkpoint.pretrained.encoder_multiscale_dense.decoder_autoencoder.epoch10000.pth.tar --val_every 100 --freeze_enc_epoch 30 --output_dir ./pretrain_multiscale_dense_enc_autoencoder_dec_ep10000_bz4_lrenc3e-4_minlrenc8e-5_finlrenc4e-6_lrdec4e-4_minlrdec8e-5_finlrdec7e-6_useuncweight_weightdecay/ --lr_sigma_seg 5e-4 --cas_min_lr_sigma_seg 5e-5 --cas_final_lr_sigma_seg 1e-5 --lr_sigma_depth 5e-4 --cas_min_lr_sigma_depth 5e-5 --cas_final_lr_sigma_depth 1e-5 --cas_warmup_steps_sigma_seg 100 --cas_warmup_steps_sigma_depth 100 --cas_T_0_sigma_seg 400 --cas_T_0_sigma_depth 400 --batch_size 4 --final_linear_decay --use_uncloss_weight --weight_decay_enc 2e-4 --weight_decay_dec 3e-4

# test eval -> meaniou : 0.218182 | rmse : 1.167690
 CUDA_VISIBLE_DEVICES=3 python ./main.py --lr_enc 2e-4 --cas_min_lr_enc 8e-5 --cas_final_lr_enc 3e-6 --lr_dec 2e-4 --cas_min_lr_dec 8e-5 --cas_final_lr_dec 1e-5 --cas_warmup_steps_enc 50 --cas_warmup_steps_dec 100 --max_iter 2301 --cas_T_0_enc 1000 --cas_T_0_dec 400 --load_init 1 --load_pretrained 1 --load_resume 0 --init_chkpt_file_enc ./weights/pretrained_hydranet_encoder.320_256.epoch10000.multiscale_dense.pth.tar --init_chkpt_file_dec ./weights/pretrained_hydranet_decoder.autoencoder.epoch10000.pth.tar --out_chkpt_file checkpoint.pretrained.encoder_multiscale_dense.decoder_autoencoder.epoch10000.pth.tar --val_every 100 --freeze_enc_epoch 100 --output_dir ./pretrain_multiscale_dense_enc_autoencoder_dec_ep10000_bz4_uncweightloss_lrenc2e-4_minlrenc8e-5_finlrenc3e-6_lrdec2e-4_minlrdec8e-5_finlrdec1e-5/ --batch_size 4 --use_uncloss_weight --final_linear_decay --lr_sigma_seg 5e-4 --lr_sigma_depth 5e-4 --cas_min_lr_sigma_seg 5e-5 --cas_final_lr_sigma_seg 1e-5 --cas_T_0_sigma_seg 300 --cas_warmup_steps_sigma_seg 100 --cas_min_lr_sigma_depth 5e-5 --cas_final_lr_sigma_depth 1e-5 --cas_T_0_sigma_depth 300 --cas_warmup_steps_sigma_depth 100


# Evaluate Command
CUDA_VISIBLE_DEVICES=0 python ./eval.py --checkpoint_file ./pretrain_multiscale_dense_enc_rand_dec6/best_checkpoint.pretrained.encoder_multiscale_dense.decoder_rand.pth.tar --output_dir ./pretrain_multiscale_dense_enc_rand_dec6

CUDA_VISIBLE_DEVICES=0 python ./eval.py --checkpoint_file ./pretrain_multiscale_dense_enc_rand_dec6_uncweightloss/best_checkpoint.pretrained.encoder_multiscale_dense.decoder_rand.pth.tar --output_dir ./pretrain_multiscale_dense_enc_rand_dec6_uncweightloss




